## 应用名称
#spring.application.name=job
## Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
## Nacos认证信息
#spring.cloud.nacos.discovery.username=nacos
#spring.cloud.nacos.discovery.password=nacos
## Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
#spring.cloud.nacos.discovery.server-addr=mse-6d50f4f0-p.nacos-ans.mse.aliyuncs.com:8848
## 注册到 nacos 的指定 namespace，默认为 public
#spring.cloud.nacos.discovery.namespace=public
## Sentinel 控制台地址
#spring.cloud.sentinel.transport.dashboard=localhost:8080
## 取消Sentinel控制台懒加载
## 默认情况下 Sentinel 会在客户端首次调用的时候进行初始化，开始向控制台发送心跳包
## 配置 sentinel.eager=true 时，取消Sentinel控制台懒加载功能
#spring.cloud.sentinel.eager=true
## 如果有多套网络，又无法正确获取本机IP，则需要使用下面的参数设置当前机器可被外部访问的IP地址，供admin控制台使用
## spring.cloud.sentinel.transport.client-ip=

server:
  port: 8281

spring:
  application:
    name: xxl-job

# xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8280/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    executor:
      appname: zloud-executor # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: /Users/zhuqijing/data/applogs/data/applogs/xxl-job/jobhandler # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#    accessToken: yudaoyuanma # 执行器通讯TOKEN [选填]：非空时启用；




