server:
  port: 8661

spring:
  application:
    name: producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      client:
        url: http://localhost:8651
        username: zqj
        password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:8601/auth/user